version: 2.1
orbs:
  docker: circleci/docker@2.1.4
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: iliatai/stable-diffusion-webui-deployment
          update-description: true
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: iliatai/stable-diffusion-webui-deployment
          remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          use-remote-docker: true
